name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.platform.name }} | "Build:" ${{ matrix.build.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows Visual Studio 2022 x64, os: windows-2022 }
        build:
          - { name: Debug }

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Configure CMake
      run: cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.build.name }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build.name }}

  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Configure CMake
      run: >
        cmake -B build -G Ninja
        -D CMAKE_BUILD_TYPE=Debug -D USE_SANITIZERS=FALSE -D BUILD_BENCHMARK=FALSE -D USE_CLANG_TIDY=TRUE
    
    - name: Analyze Code
      run: cmake --build build --target clang-tidy

    


    