name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2022 ]
        type: [ Debug ]
        preset: [ msvc-ide, clang-make ]
        include:
          - os: windows-2022
            preset: msvc-ide
            options: -DUSE_SANITIZERS=FALSE

          - os: windows-2022
            preset: clang-make
            type: Release

        exclude:
          - os: ubuntu-latest
            preset: msvc-ide

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build -S ${{ github.workspace }} --preset=${{ matrix.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.type }} ${{ matrix.options }}

    - name: Build
      run: cmake --build build --config ${{ matrix.type }}

    - name: Test
      run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.type }}

  clang-tidy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2022 ]
        preset: [ clang-make ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build -S ${{ github.workspace }} --preset=${{ matrix.preset }}

    - name: Analyze Code
      run: cmake --build build --target tidy
